version: '3.9'

services:
  dash:
    command: python3 main.py
    image: oatcp2542/cartesting:a2
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: Test.Dockerfile
    # ports:
    #   - 8050:70
    volumes:
      - ./code:/root/code
      - ./.vscode-server:/root/.vscode-server
    environment:
      - HOST=0.0.0.0
      - PORT=80